// Define global variable for example string
pub static EXAMPLE: &str =
r#"....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#..."#;
